import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { AgendaItem } from "@/components/agenda/AgendaEditor";

// Register a clean font – using built-in Helvetica family as fallback
Font.registerHyphenationCallback((word) => [word]);

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    backgroundColor: "#FFFFFF",
    paddingTop: 50,
    paddingBottom: 50,
    paddingHorizontal: 50,
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 3,
    borderBottomColor: "#2563EB",
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 26,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 10,
    color: "#6B7280",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  itemsContainer: {
    gap: 0,
  },
  item: {
    flexDirection: "row",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  itemLast: {
    borderBottomWidth: 0,
  },
  timeCol: {
    width: 72,
    paddingRight: 16,
    paddingTop: 2,
  },
  timeText: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#2563EB",
  },
  contentCol: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 3,
  },
  itemDescription: {
    fontSize: 10,
    color: "#6B7280",
    lineHeight: 1.5,
    marginBottom: 4,
  },
  metaRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 2,
  },
  metaText: {
    fontSize: 9,
    color: "#9CA3AF",
  },
  metaLabel: {
    color: "#374151",
    fontFamily: "Helvetica-Bold",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    textAlign: "center",
    fontSize: 8,
    color: "#D1D5DB",
  },
  noItems: {
    fontSize: 11,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 40,
  },
});

interface AgendaPDFDocumentProps {
  title?: string;
  eventName?: string;
  items: AgendaItem[];
}

export function AgendaPDFDocument({
  title,
  eventName,
  items,
}: AgendaPDFDocumentProps) {
  const displayTitle = title || (eventName ? `${eventName} — Agenda` : "Event Agenda");

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>{displayTitle}</Text>
          <Text style={styles.headerSubtitle}>Official Program Schedule</Text>
        </View>

        {/* Items */}
        <View style={styles.itemsContainer}>
          {items.length === 0 ? (
            <Text style={styles.noItems}>No agenda items defined.</Text>
          ) : (
            items.map((item, idx) => (
              <View
                key={item.id}
                style={[
                  styles.item,
                  ...(idx === items.length - 1 ? [styles.itemLast] : []),
                ]}
              >
                {/* Time column */}
                <View style={styles.timeCol}>
                  <Text style={styles.timeText}>{item.time || "—"}</Text>
                </View>

                {/* Content column */}
                <View style={styles.contentCol}>
                  <Text style={styles.itemTitle}>{item.title}</Text>
                  {item.description ? (
                    <Text style={styles.itemDescription}>
                      {item.description}
                    </Text>
                  ) : null}
                  <View style={styles.metaRow}>
                    {item.speaker ? (
                      <Text style={styles.metaText}>
                        <Text style={styles.metaLabel}>Speaker: </Text>
                        {item.speaker}
                      </Text>
                    ) : null}
                    {item.location ? (
                      <Text style={styles.metaText}>
                        <Text style={styles.metaLabel}>Location: </Text>
                        {item.location}
                      </Text>
                    ) : null}
                  </View>
                </View>
              </View>
            ))
          )}
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          {displayTitle} • Generated by Guest Manager
        </Text>
      </Page>
    </Document>
  );
}
